name: Test and Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run tests
      run: |
        pytest test_app.py
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
      
    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve -var="key_name=${{ secrets.SSH_KEY_NAME }}" -var="github_repo=${{ github.repository }}"
      
    - name: Get EC2 IP
      id: get_ip
      run: |
        cd terraform
        echo "::set-output name=ip::$(terraform output -raw public_ip)"
      
    - name: Wait for instance to be ready
      run: sleep 60
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.get_ip.outputs.ip }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/blog
          git pull
          pip3 install -r requirements.txt
          sudo systemctl restart blog
